---
- name: Hostname | Make sure the utility packages are installed
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - build-essential
      - jq

# Nova VMs created in citynetwork use ubuntu as the default hostname, should be changed to the VM name so that
# the kubernetes node could be initialized.
- name: Hostname | Get instance hostname from Nova metadata service
  shell:
    executable: /bin/bash
    cmd: |
      nova_hostname=$(curl -sS http://169.254.169.254/openstack/latest/meta_data.json | jq -r '.hostname')
      echo ${nova_hostname%%.novalocal}
  register: hostname_output

- name: Hostname | Ensure dbus installation as a dependency of hostnamectl
  apt:
    name: dbus
    state: present

- name: Hostname | Set hostname
  hostname:
    name: "{{ hostname_output.stdout }}"
    use: systemd

- name: Hostname | Set hostname in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp='^127\.0\.1\.1'
    line='127.0.1.1 {{ hostname_output.stdout }}'
    state=present