- name: Set fact for opentelekomcloud openrc
  set_fact:
    opentelekomcloud_openrc:
      OS_PASSWORD: '{{ opentelekomcloud_credentials.password }}'
      OS_AUTH_TYPE: '{{ opentelekomcloud_credentials.auth_type }}'
      OS_AUTH_URL: '{{ opentelekomcloud_credentials.auth_url }}'
      OS_IDENTITY_API_VERSION: '{{ opentelekomcloud_credentials.identity_api_version }}'
      OS_DOMAIN_NAME: '{{ opentelekomcloud_credentials.domain_name }}'
      OS_USER_DOMAIN_NAME: '{{ opentelekomcloud_credentials.user_domain_name }}'
      OS_PROJECT_DOMAIN_NAME: '{{ opentelekomcloud_credentials.project_domain_name }}'
      OS_PROJECT_NAME: '{{ opentelekomcloud_credentials.project_name}}'
      OS_REGION_NAME: '{{ opentelekomcloud_credentials.region_name}}'
      OS_TENANT_NAME: '{{ opentelekomcloud_credentials.project_name }}'
      OS_USERNAME: '{{ opentelekomcloud_credentials.user_name }}'
      OS_ACCESS_KEY: '{{ opentelekomcloud_credentials.access_key }}'
      OS_SECRET_KEY: '{{ opentelekomcloud_credentials.secret_key }}'
      OS_AVAILABILITY_ZONE: '{{ opentelekomcloud_credentials.availability_zone }}'
  no_log: yes
