- hosts: all
  become: yes
  tasks:
    - debug: var=ansible_all_ipv4_addresses

    - name: Test functionalities of Spark deployed on k8s cluster
      shell: |
        set -ex
        # install java8
        apt-get install openjdk-8-jdk -y
        sed -i -e '/127.0.0.1/ s/\(localhost\)/'$(hostname)' \1/' /etc/hosts
        export JAVA_HOME=$(dirname $(dirname $(update-alternatives --list javac)))

        # NOTE: the distribution step may fail due to dependencies downloading failure, so we suport retry
        for i in $(seq 1 3); do ./dev/make-distribution.sh --tgz -Pkubernetes && s=0 && break || s=$? && sleep 5; done; (exit $s)
        sleep 2000000

        pushd resource-managers/kubernetes/integration-tests
        dev/dev-run-integration-tests.sh --deploy-mode cloud --spark-master k8s://$(kubectl config view -o jsonpath='{.clusters[0].cluster.server}') --spark-tgz '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/spark-3.0.0-SNAPSHOT-bin-2.7.4.tgz' --image-repo kubespark --namespace default --service-account spark
        popd
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
