- hosts: all
  become: yes
  roles:
    - export-orange-openrc
  tasks:
    - shell:
        cmd: |
          apt-get install python-pip -y
          pip install -U python-openstackclient

          export OS_SHARE_NETWORK_ID="foobar"
          export OS_FLAVOR_ID_RESIZE="t2.small"
          export OS_FLAVOR_ID="t2.micro"
          export OS_POOL_NAME="admin_external_net"
          export OS_EXTGW_ID="$(openstack network show $OS_POOL_NAME -f value -c id)"
          export OS_IMAGE_NAME="cirros-0.3.5-x86_64-disk"
          export OS_IMAGE_ID="$(openstack image show $OS_IMAGE_NAME -f value -c id)"
          if [ -z "$OS_IMAGE_ID" ]; then
              curl -O http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
              export OS_IMAGE_ID="$(openstack image create --file ./cirros-0.3.5-x86_64-disk.img --min-disk 1 --container-format bare --disk-format raw cirros-0.3.5-x86_64-disk -f value -c id)"
              rm cirros-0.3.5-x86_64-disk.img
          fi

          _NET_PREFIX="terraform-provider-flexibleengine-orange"
          export OS_NETWORK_NAME="$_NET_PREFIX-net"
          export OS_NETWORK_ID="$(openstack network show $OS_NETWORK_NAME -f value -c id)"
          if [ -z "$OS_NETWORK_ID" ]; then
              export OS_NETWORK_ID="$(openstack network create $OS_NETWORK_NAME -f value -c id)"
              openstack subnet create --network $OS_NETWORK_ID --subnet-range 172.16.10.0/24 $_NET_PREFIX-subnet
          fi

          export OS_VPC_ID="$(openstack router show $_NET_PREFIX-vpc -f value -c id)"
          if [ -z "$OS_VPC_ID" ]; then
              export OS_VPC_ID="$(openstack router create $_NET_PREFIX-vpc -f value -c id)"
              openstack router add subnet $_NET_PREFIX-vpc $_NET_PREFIX-subnet
          fi

          set -e
          set -o pipefail
          set -x

          # Run acc test
          if [[ ! -d $GOPATH/src/github.com/Karajan-project/terraform-provider-flexibleengine/ && -d $GOPATH/src/github.com/animationzl/terraform-provider-flexibleengine ]]; then
              echo "Warning: this is a temporary workaround because this job is not triggered from official git repo."
              mkdir -p $GOPATH/src/github.com/Karajan-project/
              cp -r $GOPATH/src/github.com/animationzl/terraform-provider-flexibleengine  $GOPATH/src/github.com/Karajan-project/
              cd $GOPATH/src/github.com/Karajan-project/terraform-provider-flexibleengine
          fi

          make testacc 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env | combine(orange_openrc) }}'
