- hosts: all
  become: yes
  roles:
    - role: export-cloud-openrc
      vars:
        cloud_name: 'opentelekomcloud'
  tasks:
    - name: Clean up resources for bosh acceptance tests
      shell:
        cmd: |
          set -e
          set -x
          BUILD_ID="{{ zuul.build }}"
          sleep 7200
          openstack keypair delete microbosh-${BUILD_ID} || true
          openstack security group delete bosh-${BUILD_ID} || true
          echo "Checking residual resources: "
          openstack server list -c ID -c Name |grep bosh
          openstack server list -c ID -c Name |grep batlight
          openstack keypair list |grep bosh
          openstack security group list |grep bosh
          openstack image list |grep bosh-openstack-kvm-ubuntu-trusty-go_agent
          openstack volume list --status available |grep 64
        executable: /bin/bash
      environment: '{{ golang_env }}'
