- hosts: all
  become: yes
  vars:
    job_uid: '{{ zuul.build[:10] }}'
  roles:
    - export-cloud-openrc
  tasks:
    - name: Run Openshift Origin functional tests against {{ cloud_name }}
      shell:
        cmd: |
          set -xe
          mkdir -p '{{ ansible_user_dir }}/src/github.com/huaweicloud/'
          cd '{{ ansible_user_dir }}/src/github.com/huaweicloud/'
          git clone http://github.com/huaweicloud/openshift-ansible
          cd openshift-ansible
          pip install ansible
          pip install jinja2
          pip install shade
          pip install jmespath
          pip install dnspython
          pip install python-openstackclient
          pip install python-heatclient

          openstack keypair create "openshift-{{ job_uid }}" > "openshift-{{ job_uid }}.pem"
          chmod 400 "openshift-{{ job_uid }}.pem"

          cat << EOF > extra_vars.yml
          ---
          openshift_openstack_default_image_name: "CentOS 7.5 64bit"
          openshift_openstack_clusterid: "openshift-{{ job_uid }}"
          openshift_openstack_public_dns_domain: "huaweicloud.com"
          openshift_openstack_keypair_name: "openshift-{{ job_uid }}"
          openshift_openstack_num_infra: 1
          openshift_openstack_num_nodes: 1
          openshift_release: "{{ openshift_release | default('3.9') }}"
          EOF

          # Check prerequisites
          ansible-playbook --user root \
              -i playbooks/openstack/inventory.py \
              -i playbooks/openstack/huawei-inventory \
              --private-key "./openshift-{{ job_uid }}.pem" \
              playbooks/openstack/openshift-cluster/prerequisites.yml \
              -e @extra_vars.yml

          # Provision
          ansible-playbook --user root \
              -i playbooks/openstack/inventory.py \
              -i playbooks/openstack/huawei-inventory \
              --private-key "./openshift-{{ job_uid }}.pem" \
              playbooks/openstack/openshift-cluster/provision.yml \
              -e @extra_vars.yml

          # Install openshift cluster
          ansible-playbook --user root \
              -i playbooks/openstack/inventory.py \
              -i playbooks/openstack/huawei-inventory \
              --private-key "./openshift-{{ job_uid }}.pem"  \
              playbooks/openstack/openshift-cluster/install.yml \
              -e @extra_vars.yml
        executable: /bin/bash
      environment: '{{ global_env }}'
