- name: Run opensds unit test
  hosts: all
  roles:
    - ensure-legacy-workspace-directory
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          wget -c https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
          sudo tar -C /usr/local/ -xvzf go1.9.linux-amd64.tar.gz

          # Install env variables
          export GOPATH={{ ansible_user_dir }}
          mkdir -p $GOPATH/{bin,pkg}
          export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
          export GOBIN=$GOPATH/bin
          export OPENSDS_DIR=$GOPATH/src/github.com/opensds
          export OPENSDS_ROOT=$OPENSDS_DIR/opensds

          # OpenSDS Download
          if [ ! -d $OPENSDS_DIR ]; then
            mkdir -p $OPENSDS_DIR
          fi
          cd $OPENSDS_DIR
          if [ ! -d $OPENSDS_ROOT ]; then
            git clone https://github.com/opensds/opensds.git -b development
          fi
          cd $OPENSDS_ROOT

          # Start unit test.
          go test -v github.com/opensds/opensds/client/... -cover
          go test -v github.com/opensds/opensds/pkg/... -cover
          go test -v github.com/opensds/opensds/contrib/... -cover
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ zuul | zuul_legacy_vars }}'
