- hosts: all
  become: yes
  tasks:
    - pause:
        minutes: 30
    - name: Clone opnstacksdk
      git:
        repo: http://git.openstack.org/openstack/openstacksdk
        dest: '{{ ansible_user_dir }}/src/git.openstack.org/openstack/openstacksdk'

- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - install-devstack
    - ensure-tox
    - role: tox
      vars:
        tox_install_siblings: true
        zuul_work_dir: '{{ ansible_user_dir }}/src/git.openstack.org/openstack/openstacksdk'
        tox_envlist: ansible
