- hosts: k8s-master
  become: yes
  vars:
    cases:
      - { case: "case1", name: "vc-tfbenchmarks-1", ps_replicas: 1, worker_replicas: 1,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 2}
      - { case: "case2", name: "vc-tfbenchmarks-1", ps_replicas: 1, worker_replicas: 2,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 4000m, worker_mem: 3800Mi, minavailable: 3}
      - { case: "case3", name: "vc-tfbenchmarks-1", ps_replicas: 2, worker_replicas: 4,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 6}
      - { case: "case4", name: "vc-tfbenchmarks-1", ps_replicas: 2, worker_replicas: 4,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 6}
      - { case: "case4", name: "vc-tfbenchmarks-2", ps_replicas: 2, worker_replicas: 4,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 6}
      - { case: "case4", name: "vc-tfbenchmarks-3", ps_replicas: 2, worker_replicas: 4,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 6}
      - { case: "case4", name: "vc-tfbenchmarks-4", ps_replicas: 2, worker_replicas: 4,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 6}
      - { case: "case4", name: "vc-tfbenchmarks-5", ps_replicas: 2, worker_replicas: 4,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 6}
      - { case: "case5", name: "vc-tfbenchmarks-1", ps_replicas: 2, worker_replicas: 4,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 6}
      - { case: "case5", name: "vc-tfbenchmarks-2", ps_replicas: 2, worker_replicas: 4,
          ps_cpu: 1000m, ps_mem: 1000Mi, worker_cpu: 2000m, worker_mem: 3800Mi, minavailable: 6}
    # We only test the typical case case4 without case1,2,3, otherwise, it will take very long time.
    cases_to_run:
      - case4
  tasks:
    - name: prepare k8s namespaces for volcano and TFjobs
      shell:
        cmd: |
          set -o pipefail
          set -ex
          cat <<EOF | kubectl create -f -
          apiVersion: v1
          kind: Namespace
          metadata:
           name: volcano
           annotations:
             scheduler.alpha.kubernetes.io/node-selector: env=system
          spec: {}
          status: {}
          EOF

          cat <<EOF | kubectl create -f -
          apiVersion: v1
          kind: Namespace
          metadata:
           name: vc-tfbenchmarks
           annotations:
             scheduler.alpha.kubernetes.io/node-selector: env=workload
          spec: {}
          status: {}
          EOF
          sed -i '/--enable-admission-plugins/ s/$/,PodNodeSelector/' /etc/kubernetes/manifests/kube-apiserver.yaml
          sleep 30
        executable: /bin/bash

    - name: create vc-tfbenchmarks directory
      file: path="{{ ansible_user_dir }}/workspace/vc-tfbenchmarks/{{ item }}" state=directory
      with_items: "{{ cases | json_query('[*].case')|unique }}"

    - name: customize volcano tfbenchmarks templates
      become: yes
      template:
        dest: "{{ ansible_user_dir }}/workspace/vc-tfbenchmarks/{{ item.case }}/{{ item.name }}.yaml"
        src: "vc-tfbenchmarks.yaml.j2"
      vars:
        vc_tfbenchmarks_name: "{{ item.name }}"
        ps_replicas: "{{ item.ps_replicas }}"
        worker_replicas: "{{ item.worker_replicas }}"
        ps_cpu: "{{ item.ps_cpu }}"
        ps_mem: "{{ item.ps_mem }}"
        worker_cpu: "{{ item.worker_cpu }}"
        worker_mem: "{{ item.worker_mem }}"
        minavailable: "{{ item.minavailable }}"
      with_items: "{{ cases }}"

    - name: deploy volcano
      shell: |
        set -o pipefail
        set -ex
        mkdir -p src/volcano.sh/
        git clone https://github.com/volcano-sh/volcano src/volcano.sh/volcano -b release-0.1
        pushd src/volcano.sh/volcano
        curl -L https://git.io/get_helm.sh | bash
        helm init
        kubectl --namespace kube-system create serviceaccount tiller
        kubectl create clusterrolebinding tiller-cluster-rule \
         --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
        kubectl --namespace kube-system patch deploy tiller-deploy \
         -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'

        sleep 30
        kubectl -n kube-system wait --timeout 300s --for condition=ready pod --all
        helm version
        helm plugin install installer/chart/volcano/plugins/gen-admission-secret
        helm gen-admission-secret --service volcano-trial-admission-service --namespace volcano
        helm install installer/chart/volcano --namespace volcano --name volcano-trial --set basic.image_tag_version=fix_timestamp
        sleep 10
        kubectl -n volcano get pods -o wide
        kubectl -n volcano get svc
        kubectl -n volcano wait --timeout 300s --for condition=ready pod --all
      args:
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}'

    - name: run tensorflow benchmarks
      shell: |
        set -o pipefail
        set -ex
        for case in {{ cases_to_run  | join(' ') }}
        do
            kubectl -n vc-tfbenchmarks create -f "{{ ansible_user_dir }}/workspace/vc-tfbenchmarks/${case}"
            sleep 20
            kubectl -n vc-tfbenchmarks get job.batch.volcano.sh
            kubectl -n vc-tfbenchmarks get pods -o wide

            function tfjobs_status() {
                kubectl -n vc-tfbenchmarks get job.batch.volcano.sh -o jsonpath='{range .items[*]}{.status.state.phase}{"\n"}'|sort|uniq
            }
            export -f tfjobs_status

            function get_tfjobs() {
                kubectl -n vc-tfbenchmarks get job.batch.volcano.sh -o=custom-columns=NAME:.metadata.name,STATUS:.status.state.phase,CREATED_AT:.metadata.creationTimestamp
            }
            export -f get_tfjobs

            exit_code=0
            set +x
            timeout 72000 bash -c '
                while :
                do
                    job_status=$(tfjobs_status)
                    echo "======================================================="
                    if [[ "Terminated Completed Failed" =~ "$(echo $job_status)" ]]; then
                        echo "All TFjobs run complate!"
                        get_tfjobs
                        break
                    else
                        echo "There are TFjobs still in running or inqueue status..."
                        get_tfjobs
                    fi
                    sleep 30
                done
                ' || exit_code=$?
            set -x
            set +e
            result_path="{{ ansible_user_dir }}/workspace/test_results/volcano/${case}"
            mkdir -p ${result_path}/{pods_logs,jobs_logs}

            if [ ! -d "${result_path}/../jobs_resources" ]; then
                mkdir -p ${result_path}/../jobs_resources
                cp -r vc-tfbenchmarks/*  ${result_path}/../jobs_resources/
            fi
            if [ ! -f "${result_path}/../results.csv" ]; then
                echo 'case,job,started_at,complated_at,duration' >> ${result_path}/../results.csv
            fi

            jobs_names=$(kubectl -n vc-tfbenchmarks get job.batch.volcano.sh -o custom-columns=NAME:.metadata.name --no-headers |grep benchmark)
            for job_name in ${jobs_names}; do
                kubectl -n vc-tfbenchmarks describe job.batch.volcano.sh ${job_name} > ${result_path}/jobs_logs/${job_name}.log
                complated_at=`cat ${result_path}/jobs_logs/${job_name}.log |grep 'Completion Time:'|awk '{print $(NF)}'`
                started_at=`cat ${result_path}/jobs_logs/${job_name}.log |grep 'Start Time:'|awk '{print $(NF)}'`
                started_at_ts=`date -d ${started_at} +%s`
                complated_at_ts=`date -d ${complated_at} +%s`
                duration=''
                if [ -n "${complated_at_ts}" ]; then
                    duration=`echo $(($complated_at_ts-$started_at_ts)) |awk '{print strftime("%H:%M:%S",$1)}'`
                fi
                echo "${case},${job_name},${started_at},${complated_at},${duration}" >> ${result_path}/../results.csv
            done

            jobs_pods=$(kubectl -n vc-tfbenchmarks get pods -o custom-columns=NAME:.metadata.name --no-headers |grep benchmark)
            for job_pod in ${jobs_pods}; do
                kubectl -n vc-tfbenchmarks logs ${job_pod} > ${result_path}/pods_logs/${job_pod}.log
            done

            kubectl -n vc-tfbenchmarks delete -f "{{ ansible_user_dir }}/workspace/vc-tfbenchmarks/${case}"
            sleep 180
            kubectl -n vc-tfbenchmarks get job.batch.volcano.sh
        done
      args:
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'

    - name: volcano env cleanup
      shell: |
        set -x
        helm delete volcano-trial --purge
        sleep 60
        kubectl get pods -o wide -A
        kubectl -n volcano get pods -o wide
      args:
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}'
