- name: install docker, kubernetes {{ k8s_version }} and etcd {{ etcd_version }}, disable iptables
  shell:
    cmd: |
      set -x
      set -e

      # # Stopping firewall and allow all traffic
      # iptables -F
      # iptables -X
      # iptables -t nat -F
      # iptables -t nat -X
      # iptables -t mangle -F
      # iptables -t mangle -X
      # iptables -P INPUT ACCEPT
      # iptables -P FORWARD ACCEPT
      # iptables -P OUTPUT ACCEPT

      # # Install docker
      # apt update -y
      # apt install -y docker.io

      # # Install etcd
      # wget https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
      # tar -zxf etcd-{{ etcd_version }}-linux-amd64.tar.gz
      # cp etcd-{{ etcd_version }}-linux-amd64/etcd{,ctl} /usr/local/bin/

      # # Build k8s cmd
      # git clone https://github.com/kubernetes/kubernetes ${GOPATH}/src/k8s.io/kubernetes -b '{{ k8s_version }}'
      # make -C ${GOPATH}/src/k8s.io/kubernetes WHAT="cmd/kubectl cmd/hyperkube"
      echo '{{ golang_env }}'
      echo '{{ golang_env.GOPATH }}'
    executable: /bin/bash
  environment: '{{ golang_env }}'
