- name: Ensure legacy workspace directory
  file:
    path: '{{ ansible_user_dir }}/workspace'
    state: directory

- name: Install golang version 1.9
  become: yes
  shell: |
    set -e
    set -x
    wget -c https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
    sudo tar -C /usr/local/ -xvzf go1.9.linux-amd64.tar.gz
    echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile.d/goenv.sh
  args:
    chdir: "{{ ansible_user_dir }}/workspace"
    executable: /bin/bash

# TODO delete the mkdir/cp instructions when move to offcial project
- name: Run terraform acceptance test
  shell: |
    set -x
    set -e
    # Install env variables
    export GOPATH={{ ansible_user_dir }}
    export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
    export GOBIN=$GOPATH/bin
    mkdir -p $GOPATH/{bin,pkg}

    # TODO the following two lines should be removed after we swith to run CI
    # with official repo
    mkdir -p $GOPATH/src/github.com/hashicorp/
    cp -r $GOPATH/src/github.com/theopenlab/terraform  $GOPATH/src/github.com/hashicorp/

    cd $GOPATH/src/github.com/hashicorp/terraform
    make testacc TEST=./
  args:
    chdir: "{{ ansible_user_dir }}/workspace"
    executable: /bin/bash
