- hosts: all
  become: yes
  roles:
    - create-single-k8s-cluster-with-kubeadm
  tasks:
    - name: Test
      shell:
        cmd: |
          set -e
          set -x
          sleep 10800
        executable: /bin/bash
      environment: '{{ global_env }}'