- hosts: all
  become: yes
  roles:
    - install-golang
    - role: update-system-wide-path
      extra_path: '/usr/local/go/bin:{{ ansible_user_dir }}/bin'
    - role: set-system-wide-env
      extra_env:
        GOPATH: '{{ ansible_user_dir }}'
  tasks:
    - shell:
        cmd: |
          source /etc/environment
        executable: /bin/bash

  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/home/zuul/bin'
    GOPATH: '/home/zuul'