- hosts: all
  become: yes
  roles:
    - ensure-legacy-workspace-directory
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          wget -c https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
          sudo tar -C /usr/local/ -xvzf go1.9.linux-amd64.tar.gz

          # Install env variables
          export GOPATH={{ ansible_user_dir }}
          mkdir -p $GOPATH/{bin,pkg}
          export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
          export GOBIN=$GOPATH/bin

          if [[ ! -d $GOPATH/src/github.com/gophercloud/gophercloud/ ]]; then
              echo "Warnning: this is a temporary workaround because this job is not triggered from official git repo."
              mkdir -p $GOPATH/src/github.com/gophercloud/
              cp -r $GOPATH/src/github.com/theopenlab/gophercloud  $GOPATH/src/github.com/gophercloud/
              cd $GOPATH/src/github.com/gophercloud/gophercloud
          fi

          go get ./... || true
          go get -u github.com/jstemmer/go-junit-report
          XML_LOG_FILE='{{ ansible_user_dir }}/workspace/test_results.xml'
          HTML_LOG_FILE='{{ ansible_user_dir }}/workspace/test_results.html'
          ./script/unittest -v 2>&1 | tee /dev/tty | go-junit-report > $XML_LOG_FILE

          sudo apt install python-pip -y
          pip install junit2html
          junit2html $XML_LOG_FILE $HTML_LOG_FILE
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ zuul | zuul_legacy_vars }}'
