- hosts: all
  become: yes
  roles:
    - ensure-legacy-workspace-directory
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          wget -c https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
          sudo tar -C /usr/local/ -xzf go1.9.linux-amd64.tar.gz

          # Install env variables
          export GOPATH={{ ansible_user_dir }}
          mkdir -p $GOPATH/{bin,pkg}
          export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
          export GOBIN=$GOPATH/bin

          if [[ ! -d $GOPATH/src/github.com/gophercloud/gophercloud/ ]]; then
              echo "Warnning: this is a temporary workaround because this job is not triggered from official git repo."
              mkdir -p $GOPATH/src/github.com/gophercloud/
              cp -r $GOPATH/src/github.com/theopenlab/gophercloud  $GOPATH/src/github.com/gophercloud/
              cd $GOPATH/src/github.com/gophercloud/gophercloud
          fi

          TEST_RESULTS_TXT='{{ ansible_user_dir }}/workspace/test_results.txt'
          TEST_RESULTS_XML='{{ ansible_user_dir }}/workspace/test_results.xml'
          TEST_RESULTS_HTML='{{ ansible_user_dir }}/workspace/test_results.html'

          go get ./... || true
          ./script/unittest -v 2>&1 | tee -a $TEST_RESULTS_TXT

          go get -u github.com/jstemmer/go-junit-report
          go-junit-report < $TEST_RESULTS_TXT > $TEST_RESULTS_XML
          apt install npm -y > /dev/null
          npm install -g npm > /dev/null
          npm install -g n > /dev/null
          n stable > /dev/null
          npm install -g xunit-viewer > /dev/null
          xunit-viewer --results=$TEST_RESULTS_XML --output=$TEST_RESULTS_HTML --title='OpenLab Test Result'
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ zuul | zuul_legacy_vars }}'
