- hosts: all
  roles:
    - set-golang-env-fact
  tasks:
    - shell:
        cmd: |
          set -e
          set -x

          if [[ ! -d $GOPATH/src/github.com/gophercloud/gophercloud/ ]]; then
              echo "Warnning: this is a temporary workaround because this job is not triggered from official git repo."
              mkdir -p $GOPATH/src/github.com/gophercloud/
              cp -r $GOPATH/src/github.com/theopenlab/gophercloud  $GOPATH/src/github.com/gophercloud/
              cd $GOPATH/src/github.com/gophercloud/gophercloud
          fi

          go get ./... || true
          ./script/unittest -v 2>&1 > $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
