- name: (Deprecated, instead by "install-docker") Install Runtime Docker CE using the repository
  shell:
    cmd: |
      set -x
      set -e

      # Set up the repository:
      ## Update the apt package index
      apt-get update

      ## Install packages to allow apt to use a repository over HTTPS
      apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common

      ## Add Dockerâ€™s official GPG key
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      ## Add docker apt repository.
      add-apt-repository \
         "deb [arch="{{ arch }}"] https://download.docker.com/linux/ubuntu \
         $(lsb_release -cs) \
         stable"

      # Install docker ce.
      apt-get update
      if [[ "{{ docker_ce_version }}" == "latest" ]]; then
          apt-get install -y docker-ce
      else
          apt-get install docker-ce=$(apt-cache madison docker-ce |grep "{{ docker_ce_version }}" | head -n 1 | awk '{print $3}') -y
      fi

      # Setup daemon.
      cat > /etc/docker/daemon.json <<EOF
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
      EOF
      if [[ "{{ arch }}" != "arm64" ]]; then
        # Add the exec-opts in 2nd line
        sed -i '1a \ \ "exec-opts": ["native.cgroupdriver={{ docker_vcgroupdriver }}"],' /etc/docker/daemon.json
      fi

      mkdir -p /etc/systemd/system/docker.service.d

      iptables -F
      # Restart docker.
      systemctl daemon-reload
      systemctl restart docker

    executable: /bin/bash

