- name: Ensure legacy workspace directory
  file:
    path: '{{ ansible_user_dir }}/workspace'
    state: directory

- shell: |
    set -x
    set -e
    wget -c https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
    sudo tar -C /usr/local/ -xvzf go1.9.linux-amd64.tar.gz

# TODO delete the mkdir/cp instructions when move to offcial project
- name: Run terraform provider openstack acceptance test
  shell: |
    set -x
    set -e
    # Install env variables
    export GOPATH={{ ansible_user_dir }}
    export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
    export GOBIN=$GOPATH/bin

    # Prep the testing environment by creating the required testing resources and environment variables
    pushd /opt/stack/new/devstack
    source openrc admin admin
    nova flavor-create m1.acctest 99 512 5 1 --ephemeral 10
    nova flavor-create m1.resize 98 512 6 1 --ephemeral 10
    _NETWORK_ID=$(openstack network show private -c id -f value)
    _EXTGW_ID=$(openstack network show public -c id -f value)
    _IMAGE=$(openstack image list | grep -i cirros | head -n 1)
    _IMAGE_ID=$(echo $_IMAGE | awk -F\| '{print $2}' | tr -d ' ')
    _IMAGE_NAME=$(echo $_IMAGE | awk -F\| '{print $3}' | tr -d ' ')
    echo export OS_IMAGE_NAME="$_IMAGE_NAME" >> openrc
    echo export OS_IMAGE_ID="$_IMAGE_ID" >> openrc
    echo export OS_NETWORK_ID=$_NETWORK_ID >> openrc
    echo export OS_EXTGW_ID=$_EXTGW_ID >> openrc
    echo export OS_POOL_NAME="public" >> openrc
    echo export OS_FLAVOR_ID=99 >> openrc
    echo export OS_FLAVOR_ID_RESIZE=98 >> openrc
    echo export OS_SHARE_NETWORK_ID=foobar >> openrc
    source openrc demo demo
    sleep 7200
    popd

    # Run acc test
    mkdir -p $GOPATH/{bin,pkg}

    if [[ ! -d $GOPATH/src/github.com/terraform-providers/terraform-provider-openstack/ ]]; then
        echo "Warnning: this is a temporary workaround because this job is not triggered from official git repo."
        mkdir -p $GOPATH/src/github.com/terraform-providers/
        cp -r $GOPATH/src/github.com/theopenlab/terraform-provider-openstack  $GOPATH/src/github.com/terraform-providers/
    fi
    cd $GOPATH/src/github.com/terraform-providers/terraform-provider-openstack
    TF_ACC=1 go test ./openstack -v -timeout 120m
  args:
    executable: /bin/bash
