- import_playbook: common.yaml

# NOTE: Some tests should not be ran under root.
- hosts: all
  become: yes
  tasks:
    # Todo(wxy): Frocksdb doesn't have ARM release. Build and install it locally currently.
    - name: Build and install frocksdb
      shell:
        cmd: |
          git clone https://github.com/dataArtisans/frocksdb.git
          cd frocksdb
          git checkout origin/FRocksDB-5.17.2
          sudo apt update
          sudo apt install -y gcc g++ make
          export DEBUG_LEVEL=0
          make -j8 rocksdbjava

          mvn install:install-file -DgroupId=com.data-artisans \
          -DartifactId=frocksdbjni -Dversion=5.17.2-artisans-2.0 \
          -Dpackaging=jar -Dfile=java/target/rocksdbjni-5.17.2-linux64.jar
      args:
        executable: /bin/bash
        chdir: '/opt'
      environment: '{{ global_env }}'

    - name: Build Flink libraies
      shell:
        cmd: |
          set -xe
          mvn clean install -nsu -Dflink.convergence.phase=install -Pcheck-convergence -Dflink.forkCount=2 \
          -Dflink.forkCountTestPackage=2 -Dmaven.javadoc.skip=true -B -DskipTests -Dhadoop.version=2.8.3 \
          -Dinclude_hadoop_aws -Dscala-2.11 -am -pl flink-libraries/flink-cep,flink-libraries/flink-cep-scala,\
          flink-libraries/flink-state-processing-api,flink-table/flink-table-common,flink-table/flink-table-api-java,\
          flink-table/flink-table-api-scala,flink-table/flink-table-api-java-bridge,flink-table/flink-table-api-scala-bridge,\
          flink-table/flink-table-planner,flink-table/flink-sql-client
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    - name: Test Flink libraies
      shell:
        cmd: |
          set -xe
          mvn verify -nsu -Dflink.forkCount=2 -Dflink.forkCountTestPackage=2 -Dfast -B -Pskip-webui-build \
          -Dflink.tests.force-openssl -Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11 -fn \
          -pl flink-libraries/flink-cep,flink-libraries/flink-cep-scala,flink-libraries/flink-state-processing-api,\
          flink-table/flink-table-common,flink-table/flink-table-api-java,flink-table/flink-table-api-scala,\
          flink-table/flink-table-api-java-bridge,flink-table/flink-table-api-scala-bridge,flink-table/flink-table-planner,\
          flink-table/flink-sql-client
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    - name: Build Flink blink_planner
      shell:
        cmd: |
          set -xe
          mvn clean install -nsu -Dflink.convergence.phase=install -Pcheck-convergence -Dflink.forkCount=2 \
          -Dflink.forkCountTestPackage=2 -Dmaven.javadoc.skip=true -B -DskipTests -Dhadoop.version=2.8.3 \
          -Dinclude_hadoop_aws -Dscala-2.11 -am -pl flink-table/flink-table-planner-blink,flink-table/flink-table-runtime-blink
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    - name: Test Flink blink_planner
      shell:
        cmd: |
          set -xe
          mvn verify -nsu -Dflink.forkCount=2 -Dflink.forkCountTestPackage=2 -Dfast -B -Pskip-webui-build \
          -Dflink.tests.force-openssl -Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11 -fn \
          -pl flink-table/flink-table-planner-blink,flink-table/flink-table-runtime-blink
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
