- import_playbook: common.yaml

- hosts: all
  become: yes
  tasks:
    # Todo(wxy): Frocksdb doesn't have ARM release. Build and install it locally currently.
    - name: Build and install frocksdb
      shell:
        cmd: |
          git clone https://github.com/dataArtisans/frocksdb.git
          cd frocksdb
          sudo apt install -y gcc g++ make
          export DEBUG_LEVEL=0
          make -j8 rocksdbjavastatic

          mvn install:install-file -DgroupId=com.data-artisans \
          -DartifactId=frocksdbjni -Dversion=5.17.2-artisans-2.0 \
          -Dpackaging=jar -Dfile=java/target/rocksdbjni-5.17.2-linux64.jar
      args:
        executable: /bin/bash
        chdir: '/opt'
      environment: '{{ global_env }}'

    - name: Build Flink misc
      shell:
        cmd: |
          set -xe

          export PROFILE="-Dflink.forkCount=2 -Dflink.forkCountTestPackage=2 -Dfast -Pskip-webui-build -DskipTests -Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
          source tools/ci/stage.sh

          mvn clean install -nsu -B $PROFILE
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    - name: Test Flink misc
      shell:
        cmd: |
          set -xe

          export PROFILE="-Dflink.forkCount=2 -Dflink.forkCountTestPackage=2 -Dfast  -Pskip-webui-build -Dflink.tests.with-openssl -Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11"
          source tools/ci/stage.sh

          negated_core=\!${MODULES_CORE//,/,\!}
          negated_libraries=\!${MODULES_LIBRARIES//,/,\!}
          negated_blink_planner=\!${MODULES_BLINK_PLANNER//,/,\!}
          negated_kafka_gelly=\!${MODULES_KAFKA_GELLY//,/,\!}
          negated_connectors=\!${MODULES_CONNECTORS//,/,\!}
          negated_tests=\!${MODULES_TESTS//,/,\!}
          modules_misc="$negated_core,$negated_libraries,$negated_blink_planner,$negated_connectors,$negated_kafka_gelly,$negated_tests"

          mvn verify -nsu -B $PROFILE -pl $modules_misc
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
