- hosts: all
  become: yes
  tasks:
    - name: clean up iptable rules
      shell: iptables -F

    - name: Use huaweicloud repo
      shell: wget -O /etc/apt/sources.list https://repo.huaweicloud.com/repository/conf/Ubuntu-Ports-xenial.list && apt update

    - name: Install Pre requirements
      shell: apt install -y openssl libssl-dev libffi-dev python-dev python3-dev libevent-dev

    - name: Update resolv.conf
      shell: sed -i 's/nameserver 127.0.0.1/nameserver 8.8.8.8/' /etc/resolv.conf

    - name: Install java11
      shell:
        cmd: |
          wget https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-05-13-07-53/OpenJDK11U-jdk_aarch64_linux_hotspot_2020-05-13-07-53.tar.gz
          tar xvf OpenJDK11U-jdk_aarch64_linux_hotspot_2020-05-13-07-53.tar.gz
      args:
        executable: /bin/bash
        chdir: '/opt'
      environment: '{{ global_env }}'

    - name: Install scala211
      shell:
        cmd: |
          wget --no-check-certificate https://downloads.lightbend.com/scala/2.11.0/scala-2.11.0.tgz
          tar -zxvf scala-2.11.0.tgz -C /usr/local
      args:
        executable: /bin/bash
        chdir: '/opt'
      environment: '{{ global_env }}'

    - name: Set java11 and scala211 env vars
      set_fact:
        scala211_java11_env:
          JAVA_HOME: "/opt/jdk-11.0.8+1/"
          PATH: '/opt/jdk-11.0.8+1/bin:/usr/local/scala-2.11.0/bin:{{ ansible_env.PATH }}'
      no_log: yes

    - name: Merge java11 and scala211 env vars into global env
      set_fact:
        global_env: '{{ global_env | combine(scala211_java11_env) }}'
      no_log: yes

    - name: Show installed JAVA & scala info
      shell: |
        javac -version
        java -version
        scala -version

        # scala 2.11.0 returns error 1 even there is no error. Ignore the error.
        exit 0
      args:
        executable: /bin/bash
      environment: '{{ global_env }}'

    - name: Install docker
      shell: apt install -y docker.io containerd

    - name: Install docker compose
      shell: pip3 install docker-compose

- hosts: all
  become: yes
  roles:
    - role: install-maven
      maven_version: '3.2.5'

- hosts: all
  become: yes
  tasks:
    # Todo(wxy): Frocksdb doesn't have ARM release. Build and install it locally currently.
    - name: Build and install frocksdb
      shell:
        cmd: |
          git clone https://github.com/dataArtisans/frocksdb.git
          cd frocksdb
          sudo apt install -y gcc g++ make
          export DEBUG_LEVEL=0
          make -j8 rocksdbjavastatic

          mvn install:install-file -DgroupId=com.data-artisans \
          -DartifactId=frocksdbjni -Dversion=5.17.2-artisans-2.0 \
          -Dpackaging=jar -Dfile=java/target/rocksdbjni-5.17.2-linux64.jar
      args:
        executable: /bin/bash
        chdir: '/opt'
      environment: '{{ global_env }}'

    - name: Build Flink
      shell:
        cmd: |
          mvn clean install -DskipTests
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    - name: Hack - Use arm64 docker image
      shell:
         cmd: |
           # https://github.com/apache/flink-docker/pull/23
           sed -i 's/\/apache/\/wangxiyuan/' flink-end-to-end-tests/test-scripts/common_docker.sh
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    - name: Run e2e test - jdk11
      shell:
        cmd: |
          set -xo pipefail

          PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -Dinclude_hadoop_aws -Dscala-2.11 -Djdk11 -Pe2e-hadoop" FLINK_DIR=`pwd`/build-target flink-end-to-end-tests/run-nightly-tests.sh
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
