---
- name: Install master of Docker machine from source
  block:
    - name: config golang
      include_role: name=config-golang
    - name: install Docker machine from source
      shell: |
        set -ex
        go get github.com/docker/machine
        sleep 3000
        cd $GOPATH/github.com/docker/machine
        make build
        docker-machine version
      environment: '{{ global_env }}'
  when:
    - docker_machine_version == "master"

- name: Install relased packages of Docker machine
  block:
    - name: Check if has satisfied Docker machine installed
      shell: docker-machine version |grep -Eo '([0-9]+\.)+[0-9]+'
      ignore_errors: yes
      register: curr_docker_machine_version

    - name: Download the required Docker machine binary
      get_url:
        url: '{{ docker_machine_download_url }}'
        dest: /usr/local/bin/docker-machine
      when:
        - curr_docker_machine_version.stdout != docker_machine_version
  when:
    - docker_machine_version != "master"
