- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - install-devstack
  tasks:
    - name: Run openstacksdk ansible functional tests against a master devstack
      shell:
        cmd: |
          set -e
          set -o pipefail
          set -x
          pip install tox
          pip install -e '{{ zuul.project.src_dir }}'
          ansible --version
          pip show ansible
          git clone http://git.openstack.org/openstack/openstacksdk
          cd openstacksdk
          sleep 7200
          tox -eansible
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}'
      environment: '{{ global_env }}'