- hosts: all
  become: yes
  tasks:
    - name: Clean up resources for csi cinder acceptance tests
      shell:
        cmd: |
          set -e
          set -x
          kubectl="$GOPATH/src/k8s.io/kubernetes/cluster/kubectl.sh"
          "$kubectl" config use-context local
          "$kubectl" delete -f examples/cinder-csi-plugin/nginx.yaml
          "$kubectl" delete -f manifests/cinder-csi-plugin
        executable: /bin/bash
        chdir: '{{ k8s_specific_src_dir }}'
      environment: '{{ golang_env }}'
