- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          set -x
          echo '{{ zuul.executor.log_root }}'/zuul-info/inventory.yaml
        executable: /bin/bash
      delegate_to: localhost

    - name: Copy files from node
      synchronize:
        src: '{{ zuul.executor.log_root }}'/zuul-info/inventory.yaml
        dest: '{{ ansible_user_dir }}/workspace'
        mode: push
        copy_links: true
        verify_host: true

    - shell:
        cmd: |
          set -x
          grep -m 1 provider: inventory.yaml | awk '{print $2}'
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'

    - shell:
        cmd: |
          sleep 3600
          apt-get install python-pip -y
          pip install -U python-openstackclient
          # NOTE: the following commands may include sensitive information please do not print in job logs
          export OS_PASSWORD="`echo {{ telekom_credentials.password }}`"
          export OS_AUTH_TYPE="`echo {{ telekom_credentials.auth_type }}`"
          export OS_AUTH_URL="`echo {{ telekom_credentials.auth_url }}`"
          export OS_IDENTITY_API_VERSION="`echo {{ telekom_credentials.identity_api_version }}`"
          export OS_DOMAIN_NAME="`echo {{ telekom_credentials.domain_name }}`"
          export OS_PROJECT_NAME="`echo {{ telekom_credentials.project_name}}`"
          export OS_REGION_NAME="`echo {{ telekom_credentials.region_name}}`"
          export OS_TENANT_NAME="`echo {{ telekom_credentials.project_name }}`"
          export OS_USERNAME="`echo {{ telekom_credentials.user_name }}`"
          export OS_ACCESS_KEY="`echo {{ telekom_credentials.access_key }}`"
          export OS_SECRET_KEY="`echo {{ telekom_credentials.secret_key }}`"
          export OS_AVAILABILITY_ZONE="`echo {{ telekom_credentials.availability_zone }}`"

          set -o pipefail
          set -x
          export OS_SHARE_NETWORK_ID="foobar"
          export OS_FLAVOR_ID_RESIZE='computev2-1'
          export OS_FLAVOR_ID='computev1-1'
          export OS_POOL_NAME="admin_external_net"
          export OS_EXTGW_ID=`openstack network list -f value |grep admin_external_net | awk -F ' ' '{print $1}'`
          export OS_IMAGE_NAME=Community_Ubuntu_16.04_TSI_latest
          export OS_IMAGE_ID=d6944a41-5ec7-44a4-970e-ce330da390d2
          # export OS_IMAGE_NAME="cirros-0.3.5-x86_64-disk"
          # export OS_IMAGE_ID="$(openstack image show $OS_IMAGE_NAME -f value -c id)"
          # if [ -z "$OS_IMAGE_ID" ]; then
          #     curl -O http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
          #     export OS_IMAGE_ID="$(openstack image create --file ./cirros-0.3.5-x86_64-disk.img --min-disk 1 --container-format bare --disk-format raw cirros-0.3.5-x86_64-disk -f value -c id)"
          #     rm cirros-0.3.5-x86_64-disk.img
          # fi
          _NET_PREFIX="terraform-provider-opentelekomcloud"
          export OS_NETWORK_NAME="$_NET_PREFIX-net"
          export OS_NETWORK_ID="$(openstack network show $OS_NETWORK_NAME -f value -c id)"
          if [ -z "$OS_NETWORK_ID" ]; then
              export OS_NETWORK_ID="$(openstack network create $OS_NETWORK_NAME -f value -c id)"
              openstack subnet create --network $OS_NETWORK_ID --subnet-range 10.0.20.0/24 $_NET_PREFIX-subnet
          fi
          export OS_VPC_ID="$(openstack router show $_NET_PREFIX-vpc -f value -c id)"
          if [ -z "$OS_VPC_ID" ]; then
              export OS_VPC_ID="$(openstack router create $_NET_PREFIX-vpc -f value -c id)"
              openstack router add subnet $_NET_PREFIX-vpc $_NET_PREFIX-subnet
          fi
          export OS_SWIFT_ENVIRONMENT=1

          # Run except the DNS/FW/LB test 100 testcases at a time
          testcases=`go test ./opentelekomcloud/ -v -list 'Acc'`
          testcases=`echo "$testcases" | sed '$d' | grep -v -e FW -e LB`
          echo "$testcases" | xargs -t -n100 sh -c 'TF_ACC=1 go test ./opentelekomcloud/ -v -timeout 150m -run $(echo "$@" | tr " " "|")' argv0 2>&1 | tee $TEST_RESULTS_TXT

        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
