- name: Create a single k8s master cluster by minikube
  shell: |
    set -ex
    # Download minikube binary, the supported latest version is v0.30.0
    curl -Lo /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/"{{ minikube_version }}"/minikube-linux-amd64 && chmod +x /usr/local/bin/minikube
    # Download kubectl binary
    curl -Lo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/"{{ kubectl_version }}"/bin/linux/amd64/kubectl && chmod +x /usr/local/bin/kubectl
    sed -i 's/nameserver 127.0.0.1/nameserver 8.8.8.8/' /etc/resolv.conf
    minikube start --cpus 4 --memory 6144 --vm-driver=none --kubernetes-version {{ kubernetes_version }}
    # sleep for waiting cluster ready
    sleep 180
    timeout 300 bash -c '
        while :
        do
            [ -z "$(kubectl -n kube-system get pods --field-selector=status.phase!=Running)" ] && break
            sleep 5
        done
        '
    kubectl -n kube-system get all
  args:
    executable: /bin/bash
