- name: Run terraform unit test
  hosts: all
  roles:
    - set-golang-env-fact
  tasks:

    - shell:
        cmd: |
          set -e
          set -x

          if [[ ! -d $GOPATH/src/github.com/hashicorp/terraform/ ]]; then
              echo "Warnning: this is a temporary workaround because this job is not triggered from official git repo."
              mkdir -p $GOPATH/src/github.com/hashicorp/
              cp -r $GOPATH/src/github.com/theopenlab/terraform  $GOPATH/src/github.com/hashicorp/
              cd $GOPATH/src/github.com/hashicorp/terraform
          fi

          make test TESTARGS='-v' 2>&1 > $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
