- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          set -e
          set -o pipefail
          set -x

          # Run unit test
          if [[ ! -d $GOPATH/src/github.com/terraform-providers/terraform-provider-openstack/ && -d $GOPATH/src/github.com/theopenlab/terraform-provider-openstack ]]; then
              echo "Warnning: this is a temporary workaround because this job is not triggered from official git repo."
              mkdir -p $GOPATH/src/github.com/terraform-providers/
              cp -r $GOPATH/src/github.com/theopenlab/terraform-provider-openstack  $GOPATH/src/github.com/terraform-providers/
              cd $GOPATH/src/github.com/terraform-providers/terraform-provider-openstack
          fi

          make test TESTARGS='-v' 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
