- name: Create tensorflow pod
  shell:
    cmd: |
      set -x
      set -e

      mkdir /opt/aitest

      folder_name='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'
      file_name=`ls $folder_name | grep zip`

      apt install unzip -y

      sudo unzip $folder_name$file_name -d /opt/aitest

      cat > "/opt/aitest/test.yml" <<EOF
      apiVersion: v1
      kind: Pod
      metadata:
        name: ai-test
      spec:
        containers:
        - name: ai-tensorflow-cpu
          image: tensorflow/tensorflow
          ports:
          - containerPort: 7777
          command: ["/usr/local/bin/python"]
          args: ["/test/tensorflow_test.py"]
          volumeMounts:
          - mountPath: /test/
            name: exec
            readOnly: true
        hostNetwork: true
        volumes:
        - hostPath:
            path: /opt/aitest
            type: DirectoryOrCreate
          name: exec
      EOF

      export KUBECONFIG=/etc/kubernetes/admin.conf

      if ! timeout 30 sh -c "while ! kubectl get sa|grep default; do sleep 1; done"; then
        exit 1
      fi

      sleep 3600

      kubectl create -f /opt/aitest/test.yml


    executable: /bin/bash
