- hosts: all
  become: yes
  roles:
  tasks:
    - name: install required packages
      shell: |
        set -ex
        apt-get update -y

        # install java
        apt-get install default-jre -y
        apt-get install default-jdk -y
        java_home=$(dirname $(dirname $(update-alternatives --list javac)))
        echo "export JAVA_HOME=${java_home}" >> ~/.profile
        echo "export PATH=${java_home}/bin:$PATH" >> ~/.profile
        source ~/.profile

        # install mvn
        # apt-get install maven -y
        wget "https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz"
        tar xzvf apache-maven-3.6.1-bin.tar.gz
        new_path=$(realpath apache-maven-3.6.1/bin/):$PATH
        grep -q 'export PATH=' ~/.profile && sed -i "s|^export PATH=.*$|export PATH=${new_path}|" ~/.profile || echo "export PATH=${new_path}" >> ~/.profile
        source ~/.profile
        echo $PATH
        mvn --version

        # install dependencies for protobuf build
        apt-get install autoconf automake libtool -y
        sleep 72000

        # Fix protobuf-2.5.0
        cd /usr/local/src/
        wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
        wget -O protobuf-2.5.0-arm64.patch https://www.dropbox.com/s/713wql5cw9dfxhx/protobuf-2.5.0-arm64.patch?dl=0
        tar xfz protobuf-2.5.0.tar.gz
        cd protobuf-2.5.0
        patch -p1 < ../protobuf-2.5.0-arm64.patch
        apt-get install build-essential
        apt-get install automake libtool autoconf
        ./autogen.sh
        ./configure --prefix=/usr
        make
        make install
        ldconfig
        protoc --version

        cd '{{ ansible_user_dir }}/workspace'
        git clone https://git-wip-us.apache.org/repos/asf/hive.git
        cd hive
        grep "protoc:2.5.0" ./* -R -l
        sed -i 's|<protocArtifact>com.google.protobuf:protoc:2.5.0</protocArtifact>|<protocExecutable>/usr/bin/protoc</protocExecutable>|g' ./standalone-metastore/metastore-common/pom.xml
        sed -i 's|<protocArtifact>com.google.protobuf:protoc:2.5.0</protocArtifact>|<protocExecutable>/usr/bin/protoc</protocExecutable>|g' ./standalone-metastore/metastore-server/pom.xml
        git diff

        mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=2.5.0 \
            -Dclassifier=linux-aarch_64 -Dpackaging=exe -Dfile=../protobuf-2.5.0/java/target/protobuf-java-2.5.0.jar

        mvn -X -e clean package -Pdist -DskipTests | tee "{{ ansible_user_dir }}/workspace/logs/hive_build.log"
      args:
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'