---
galaxy_info:
  author: Andrew Rothstein
  description: role for installing the Oracle Java JRE/JDK
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Alpine
      versions:
        - all
  galaxy_tags:
    - development

dependencies:
  - role: andrewrothstein.unarchive-deps
    version: v1.0.10
  - role: andrewrothstein.alpine-glibc-shim
    version: v2.0.7
