- hosts: all
  become: yes
  tasks:
    - name: Build containerd
      shell:
        cmd: |
          set -xe
          apt-get update
          apt-get install -y btrfs-tools libseccomp-dev git pkg-config
          apt-get install -y golang-1.10-go
          ln -sf ../lib/go-1.10/bin/go /usr/bin/go

          go get github.com/containerd/containerd
          cd ~/go/src/github.com/containerd/containerd/
          make | tee make.txt
          make test | tee make_test.txt
          mkdir -p '{{ ansible_user_dir }}/workspace/build_results'
          cp make*.txt {{ ansible_user_dir }}/workspace/build_results
          cp -r ./bin {{ ansible_user_dir }}/workspace/build_results
        executable: /bin/bash
