- hosts: all
  become: yes
  tasks:
    - name: Install python3.7
      shell:
        cmd: |
          set -ex
          add-apt-repository -y ppa:deadsnakes/ppa
          apt update
          apt install -y python3.7 python3.7-dev
          rm /usr/bin/python3
          ln -s /usr/bin/python3.7 /usr/bin/python3
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
        executable: /bin/bash

    - name: install required packages
      shell: |
        apt update -y
        apt install kpartx qemu-utils curl python-yaml debootstrap libffi-dev libssl-dev -y
        pip install ansible==2.8.6
      args:
        executable: /bin/bash

    - name: Prepare ubuntu user for running labkeeper
      no_log: yes
      shell:
        cmd: |
          useradd -m -d /home/ubuntu -s /bin/bash ubuntu
          echo ubuntu:ubuntu | chpasswd
          cat > /etc/sudoers.d/ubuntu << EOF
          ubuntu ALL=(ALL) NOPASSWD:ALL
          EOF
          chmod 0440 /etc/sudoers.d/ubuntu
          su - ubuntu -c "
              ssh-keygen -f /home/ubuntu/.ssh/id_rsa -t rsa -N ''
              cat /home/ubuntu/.ssh/id_rsa.pub > /home/ubuntu/.ssh/authorized_keys
          "
        executable: /bin/bash

    - name: Run labkeeper functional test
      shell: |
        set -ex
        cp /home/ubuntu/.ssh/id_rsa ./openlab.pem
        chmod 600 openlab.pem
        chown ubuntu.ubuntu openlab.pem
        echo 'youneverknow' > vault-password.txt
        sleep 18000
        # Ansible will not load ansible.cfg automatically because this directory is world writable
        export ANSIBLE_CONFIG=ansible.cfg
        ansible-playbook playbooks/site.yaml -i inventory/test-allinone.yaml -e \
            "zuul_user_name=zuul-test zuul_user_group=zuul-test"
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
